# docker-compose.yml example

tor:
  image: goldy/tor-hidden-service
  links:
    - hello
    - world

hello:
  image: tutum/hello-world
  hostname: hello

world:
  image: tutum/hello-world
  hostname: world
