command: tor

user: debian-tor
group: debian-tor

secret_env:
    - '*_KEY'
    - '*_PORTS'

pre_conf_commands:
    - onions --setup-hosts

post_conf_commands:
    - timeout 3s tor > /dev/null || true
    - onions
    - chown -R debian-tor:debian-tor $HOME

debug: false
