command: tor

user: tor
group: tor

secret_env:
    - '*_KEY'
    - '*_PORTS'

pre_conf_commands:
    - onions --setup-hosts

post_conf_commands:
    - onions
    - chown -R tor:tor $HOME

reload:
    files:
        - /etc/tor/torrc

debug: false
